// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kjordan_final_project.Model;

namespace kjordan_final_project.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211206022915_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("kjordan_final_project.Model.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerID");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("kjordan_final_project.Model.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjDisc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectID");

                    b.HasIndex("OwnerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("kjordan_final_project.Model.TimeAllocation", b =>
                {
                    b.Property<int>("TimeAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdminTime")
                        .HasColumnType("REAL");

                    b.Property<double>("CommTime")
                        .HasColumnType("REAL");

                    b.Property<double>("OnsiteTime")
                        .HasColumnType("REAL");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeAllocationID");

                    b.HasIndex("OwnerID");

                    b.HasIndex("ProjectID");

                    b.ToTable("TimeAllocation");
                });

            modelBuilder.Entity("kjordan_final_project.Model.Project", b =>
                {
                    b.HasOne("kjordan_final_project.Model.Owner", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("kjordan_final_project.Model.TimeAllocation", b =>
                {
                    b.HasOne("kjordan_final_project.Model.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID");

                    b.HasOne("kjordan_final_project.Model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("kjordan_final_project.Model.Owner", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
